require("ohemilyy.plugins-setup")
require("ohemilyy.core.options")
require("ohemilyy.core.keymaps")
require("ohemilyy.core.colorscheme")
require("ohemilyy.plugins.lualine")
require("ohemilyy.plugins.colorizer")
require("ohemilyy.plugins.alpha")
require("ohemilyy.plugins.neotree")
