require("ohemilyy.plugins-setup")
require("ohemilyy.core.options")
require("ohemilyy.core.keymaps")
require("ohemilyy.core.colorscheme")
require("ohemilyy.plugins.lualine")
require("ohemilyy.plugins.colorizer")
require("ohemilyy.plugins.alpha")
require("ohemilyy.plugins.neotree")
require("ohemilyy.plugins.trouble")
require("ohemilyy.plugins.telescope")
require("ohemilyy.plugins.notify")
require("ohemilyy.plugins.todo-comments")
require("ohemilyy.plugins.lsp.configs")
require("ohemilyy.plugins.lsp.handlers").setup()
require("ohemilyy.plugins.lsp.null-ls")

vim.opt.termguicolors = true